//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaPreacher_1_.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenominationType
    {
        public int DenominationTypeId { get; set; }
        public string DenominationType1 { get; set; }
    }
}
