//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaPreacher_1_.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public long DistrictID { get; set; }
        public long StateID { get; set; }
        public int CountryID { get; set; }
        public string DistrictName { get; set; }
        public int Status { get; set; }
    }
}
