//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaPreacher_1_.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEnquiry
    {
        public long EnquiryID { get; set; }
        public long EventID { get; set; }
        public long UserID { get; set; }
        public string HelpServiceTypeIDs { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
