//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaPreacher_1_.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventHelpService
    {
        public int EventHelpServiceID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> HelpServiceTypeID { get; set; }
        public string Message { get; set; }
        public Nullable<int> IsPersonal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
