//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaPreacher_1_.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouritePreacher
    {
        public long FavouriteID { get; set; }
        public long PreacherID { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
